apiVersion: v1
kind: Service
metadata:
  name: rapidcompetition-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: rapidcompetition
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080